-- Categories Table
create table categories (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null
);

-- Videos Table
create table videos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  url text not null,
  title text not null,
  type text default 'long',
  note text,
  category_id bigint references categories(id) on delete set null
);

-- Users Table (For Admin Auth)
create table users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  username text not null unique,
  password text not null, -- Encrypted (hashed) password
  name text
);

-- Insert initial data (Optional - based on previous hardcoded data)
insert into categories (name) values
  ('스로우 매치기'),
  ('더블렉 테이크다운'),
  ('싱글렉 테이크다운'),
  ('가드에서 스윕'),
  ('가드 패스'),
  ('하프가드 스윕'),
  ('하프가드 패스');

-- You can run this in the Supabase SQL Editor.